### ISSUE TITLE
ModuleNotFoundError: No module named 'PySide.QtWebKit'

### ISSUE THREAD

**Issue by yujqiao** [xalanq/ITree#1]
## Environment
Arch Linux
Python 3.6.0
`sudo pacman -S python-pyside python-mistune`
## Error
```
Traceback (most recent call last):
  File "itree.py", line 6, in <module>
    from functions import *
  File "/home/rapiz/Source/ITree/functions.py", line 13, in <module>
    from PySide.QtWebKit import *
ModuleNotFoundError: No module named 'PySide.QtWebKit'
```

**Comment by yujqiao** [comment]
google 到了这个：https://bbs.archlinux.org/viewtopic.php?id=223579
qtwebkit已经不再维护了，所以arch不再支持pyside.qtwebkit。
这里是给开发者的解决方案 https://www.archlinux.org/todo/phasing-out-qtwebkit/

**Comment by yujqiao** [comment]
或者需要自己带上qtwebkit的依赖编译pyside……
anyway 我已经放弃了。。。
